/**
 * Pre-loaded Default Dataset from สถานะงานก่อสร้างสายส่งและสถานีไฟฟ้า_06082026.xlsx
 */
window.DEFAULT_DASHBOARD_DATA = {
  "fileName": "สถานะงานก่อสร้างสายส่งและสถานีไฟฟ้า_06082026.xlsx",
  "lastUpdated": "สิงหาคม 2569 (ข้อมูล ณ วันที่ 06/08/2569)",
  "transmissionLines": [
    {
      "no": 1,
      "project": "คพจ.1",
      "name": "สถานีไฟฟ้าสินสาคร - สถานีไฟฟ้าสมุทรสาคร 13 - สถานีไฟฟ้าสมุทรสาคร 8",
      "circuitKm": 6.85,
      "builder": "กกฟ.2",
      "progress2568": 65.0,
      "monthly2569": {
        "ม.ค.": 5.0,
        "ก.พ.": 2.0,
        "มี.ค.": 8.0,
        "เม.ย.": 5.0,
        "พ.ค.": 4.0,
        "มิ.ย.": 7.0,
        "ก.ค.": 3.0,
        "ส.ค.": 0,
        "ก.ย.": 0,
        "ต.ค.": 0,
        "พ.ย.": 0,
        "ธ.ค.": 0
      },
      "totalProgress": 99.0,
      "remarks": "งานก่อสร้างฐานรากเสาและสมอบกคอนกรีต ดำเนินการแล้ว 305 ฐาน\nงานปักเสา คอร. 22 เมตร ดำเนินการแล้ว 313 ต้น\nงานพาดสายไฟฟ้าและติดตั้งอุปกรณ์ ดำเนินการแล้ว 53,823/54,063 เมตร\nคาดการณ์แล้วเสร็จ วันที่ 16 สิงหาคม 2569 เนื่องด้วยดับไฟผู้ใช้ไฟรายใหญ่ได้"
    },
    {
      "no": 2,
      "project": "คพจ.2",
      "name": "Cut&Turn (สถานีไฟฟ้าสมุทรสาคร 4-สถานีไฟฟ้าสมุทรสาคร 5)-สถานีไฟฟ้าสมุทรสาคร 11",
      "circuitKm": 10.0,
      "builder": "กกฟ.2",
      "progress2568": 95.0,
      "monthly2569": {
        "ม.ค.": 0.0,
        "ก.พ.": 0.0,
        "มี.ค.": 1.0,
        "เม.ย.": 2.0,
        "พ.ค.": 1.0,
        "มิ.ย.": 1.0,
        "ก.ค.": 0.0,
        "ส.ค.": 0,
        "ก.ย.": 0,
        "ต.ค.": 0,
        "พ.ย.": 0,
        "ธ.ค.": 0
      },
      "totalProgress": 100.0,
      "remarks": "ชลประทานสมุทรสาคร และพื้นที่เอกชน อนุญาตให้ดำเนินการปักเสา พาดสายแล้ว\nติดตั้งเสา Monopole แล้ว 10/10 ต้น พร้อมพาดสาย"
    },
    {
      "no": 3,
      "project": "งบลงทุน",
      "name": "เพิ่มจุดจ่ายไฟที่ 2 สถานีไฟฟ้าแรงสูงกำแพงแสน (กฟผ.) ถึงสามแยกตลาดกำแพงแสน",
      "circuitKm": 2.7,
      "builder": "กกฟ.2",
      "progress2568": 5.0,
      "monthly2569": {
        "ม.ค.": 8.0,
        "ก.พ.": 15.0,
        "มี.ค.": 19.0,
        "เม.ย.": 10.0,
        "พ.ค.": 10.0,
        "มิ.ย.": 6.0,
        "ก.ค.": 27.0,
        "ส.ค.": 0,
        "ก.ย.": 0,
        "ต.ค.": 0,
        "พ.ย.": 0,
        "ธ.ค.": 0
      },
      "totalProgress": 100.0,
      "remarks": "งานก่อสร้างฐานรากเสาและสมอบกคอนกรีต ดำเนินการแล้ว 67  ฐาน\nงานปักเสา คอร. 22 เมตร ดำเนินการแล้ว 66 ต้น\nงานพาดสายไฟฟ้าและติดตั้งอุปกรณ์ ดำเนินการแล้ว 16,782 เมตร\nกำหนด AC Withstand วันที่ 9 สิงหาคม 2569"
    },
    {
      "no": 4,
      "project": "งบลงทุน(เร่งด่วน)",
      "name": "Tap line (สถานีไฟฟ้าสมุทรสาคร 6 - สถานีไฟฟ้าสินสาคร) - สถานีไฟฟ้าสมุทรสาคร 14 (ชั่วคราว)",
      "circuitKm": 7.11,
      "builder": "กกฟ.2",
      "progress2568": 90.0,
      "monthly2569": {
        "ม.ค.": 2.0,
        "ก.พ.": 3.0,
        "มี.ค.": 0.0,
        "เม.ย.": 0.0,
        "พ.ค.": 5.0,
        "มิ.ย.": 0.0,
        "ก.ค.": 0.0,
        "ส.ค.": 0,
        "ก.ย.": 0,
        "ต.ค.": 0,
        "พ.ย.": 0,
        "ธ.ค.": 0
      },
      "totalProgress": 100.0,
      "remarks": "งานก่อสร้างฐานรากเสาและสมอบกคอนกรีต ดำเนินการแล้ว 185 ฐาน\nงานปักเสา คอร. 22 เมตร ดำเนินการแล้ว 181 ต้น\nงานพาดสายไฟฟ้าและติดตั้งอุปกรณ์ ดำเนินการแล้ว 41,586/43,158 เมตร\nอยู่ระหว่างรอดับไฟเพื่อติดตั้งเสา Monopole มีแผนดำเนินการวันที่ \n24 พฤษภาคม 2569"
    },
    {
      "no": 5,
      "project": "งบลงทุน(เร่งด่วน)",
      "name": "Tap line (สถานีไฟฟ้ากาญจนบุรี 2 - สถานีไฟฟ้าพนมทวน) - สถานีไฟฟ้ากาญจนบุรี 5 (ชั่วคราว)",
      "circuitKm": 3.12,
      "builder": "ผกร.กรย.(ก3)",
      "progress2568": 0.0,
      "monthly2569": {
        "ม.ค.": 0.0,
        "ก.พ.": 0.0,
        "มี.ค.": 0.0,
        "เม.ย.": 0.0,
        "พ.ค.": 0.0,
        "มิ.ย.": 0.0,
        "ก.ค.": 25.0,
        "ส.ค.": 0,
        "ก.ย.": 0,
        "ต.ค.": 0,
        "พ.ย.": 0,
        "ธ.ค.": 0
      },
      "totalProgress": 25.0,
      "remarks": "งานปักเสา คอร. 22 เมตร ดำเนินการแล้ว 25/73 ต้น\nงานปักเสา Monopole 20 เมตร ดำเนินการแล้ว 0/4 ต้น\nฐานราก ดำเนินการแล้ว 66/69 ฐาน (ฐานเดี่ยว 65 ฐาน/คู่ 4 ฐาน)\nติดตั้ง ABS ขนาด 2000 A ใหม่ จำนวน 1 ชุด"
    }
  ],
  "substationsSummary": {
    "totalSubstations": 30,
    "completed": 24,
    "inProgress": 2,
    "procuring": 4,
    "programs": [
      {
        "name": "คพจ.1",
        "target": 10,
        "completed": 9,
        "inProgress": 0,
        "procuring": 1,
        "notes": "สมุทรสาคร 13 (คาดได้ผู้รับจ้าง Q4/69)"
      },
      {
        "name": "คพจ.2",
        "target": 16,
        "completed": 13,
        "inProgress": 0,
        "procuring": 3,
        "notes": "กระทุ่มแบน 7, อ้อมน้อย 1 (Renovate), สมุทรสาคร 13"
      },
      {
        "name": "งบลงทุนประจำปี 2568 (ชั่วคราว)",
        "target": 2,
        "completed": 2,
        "inProgress": 0,
        "procuring": 0,
        "notes": "สมุทรสาคร 17 (ช), สมุทรสาคร 14 (ช)"
      },
      {
        "name": "งบลงทุนเร่งด่วนประจำปี 2569 (ชั่วคราว)",
        "target": 2,
        "completed": 0,
        "inProgress": 2,
        "procuring": 0,
        "notes": "สมุทรสาคร 18 (ช), กาญจนบุรี 5 (ช)"
      }
    ]
  },
  "substationsDetail": [
    {
      "no": 1,
      "project": "คพจ.2",
      "name": "ท่าทราย 1 Renovate",
      "wbs": "P-TDD02.2-I-SMNS1.THS2.4",
      "contractor": "บริษัท อาร์ เอส เอส 2016 จำกัด (มหาชน)",
      "contract": "1/10/67 - 7/6/69",
      "duration": "582 \n(540+42+32)",
      "admin": "กจค.2(บก2)",
      "progress": 100.0,
      "supervisor": "นายกำพล ตุ้ยเต็มวงค์\nอก.รย.(ก3)",
      "committee": "1. นายสมชาย โคตรพัฒน์     รฝ.บก2\n2. นายพัทธนันท์ พชิราสุวรรณ์ชล     รฝ.ปบ.(ก3)\n3. นายนันทวิทย์ อุยยามวงศ์     วศก.9 กจค.2(บก1)",
      "statusText": "งานก่อสร้างแล้วเสร็จ\nAC Withstand Voltage Test เมื่อวันที่ 2 - 3 พฤษภาคม 2569"
    },
    {
      "no": 2,
      "project": "งบลงทุนเร่งด่วน ปี 2568",
      "name": "สมุทรสาคร 14 (ชั่วคราว)",
      "wbs": "I-68-I-KKHXX.IS.1000",
      "contractor": "กฟภ. ดำเนินการเอง",
      "contract": "-",
      "duration": "-",
      "admin": "กรย.(ก3)",
      "progress": 100.0,
      "supervisor": "นายวัชระ เวทีภิรมย์\nพชง.7 ผจส.กรย.(ก3)",
      "committee": "",
      "statusText": "งานก่อสร้างแล้วเสร็จ\nAC Withstand Voltage Test เมื่อวันที่ 28 - 29 มิถุนายน 2569\nจ่ายไฟวันที่ 1 กรกฎาคม 2569"
    },
    {
      "no": 3,
      "project": "งบลงทุนเร่งด่วน ปี 2568",
      "name": "สมุทรสาคร 17 (ชั่วคราว)",
      "wbs": "I-68-I-SMNXX.19.3911",
      "contractor": "กฟภ. ดำเนินการเอง",
      "contract": "-",
      "duration": "-",
      "admin": "กรย.(ก3)",
      "progress": 100.0,
      "supervisor": "นายจักรพันธ์ นรเหรียญ\nพชง.6 ผจส.กรย.(ก3)",
      "committee": "",
      "statusText": "งานก่อสร้างแล้วเสร็จ\nAC Withstand เมื่อวันที่ 20 กุมภาพันธ์ 2569 \nจ่ายไฟวันที่ 22 กุมภาพันธ์ 2569"
    },
    {
      "no": 4,
      "project": "งบลงทุนเร่งด่วน ปี 2569",
      "name": "สมุทรสาคร 18 (ชั่วคราว)",
      "wbs": "I-69-I-BNCXX.19.3904",
      "contractor": "กฟภ. ดำเนินการเอง",
      "contract": "-",
      "duration": "-",
      "admin": "กรย.(ก3)",
      "progress": 17.0,
      "supervisor": "นายจักรพันธ์ นรเหรียญ\nพชง.6 ผจส.กรย.(ก3)",
      "committee": "",
      "statusText": "รื้อถอนอุปกรณ์ป้องกัน 22,115 kV และหม้อแปลงกำลัง จากสถานีไฟฟ้าสมุทรสาคร 16 (ชั่วคราว) ได้ 80% ของงานรื้อถอน เตรียมขนย้ายไปติดตั้งและส่งคืนเศษวัสดุ ขณะนี้สถานีไฟฟ้าสมุทรสาคร 18 \n(ชั่วคราว) ปรับปรุงที่ดินแล้วเสร็จและเรียงฐานรากได้ประมาณ 70%"
    },
    {
      "no": 5,
      "project": "งบลงทุนเร่งด่วน ปี 2569",
      "name": "กาญจนบุรี 5 (ชั่วคราว)",
      "wbs": "I-69-I-KCI01.19.3907",
      "contractor": "กฟภ. ดำเนินการเอง",
      "contract": "-",
      "duration": "-",
      "admin": "กรย.(ก3)",
      "progress": 9.0,
      "supervisor": "นายพลากร จงอมรสิริเกษม\nพชง.3 ผจร.กรย.(ก3)",
      "committee": "",
      "statusText": "รื้อย้ายอุปกรณ์ป้องกัน 22,115 kV และหม้อแปลงกำลัง จากสถานีไฟฟ้าสมุทรสาคร 10 (ชั่วคราว) ได้ประมาณ 80% ของงานรื้อถอน\nขณะนี้อยู่ระหว่างปรับปรุงที่ดิน (ถมดินให้ได้ตามระดับ)"
    }
  ],
  "permits": [
    {
      "no": 1,
      "workType": "สถานีไฟฟ้า",
      "projectName": "งานก่อสร้างสถานีไฟฟ้าสมุทรสาคร 16",
      "permitDetail": "สะพานทางเชื่อมเข้าสถานีไฟฟ้า",
      "authority": "คลองส่งน้ำดำเนินสะดวก",
      "statusText": "คลองส่งน้ำฯ ให้แก้ไขปรับแบบแผนผังการขออนุญาต\nอยู่ระหว่าง กอฟ. แก้ไขแบบแผนผัง",
      "statusGroup": "revising",
      "statusLabel": "แก้ไขปรับแบบ"
    },
    {
      "no": 2,
      "workType": "สถานีไฟฟ้า",
      "projectName": "งานก่อสร้างสถานีไฟฟ้าสมุทรสาคร 13",
      "permitDetail": "แจ้งก่อสร้างสถานี",
      "authority": "เทศบาลเมืองพันท้ายนรสิงห์",
      "statusText": "เทศบาลนครพันท้ายนรสิงห์ รับทราบแล้ว \nตามหนังสือที่ สค 53503/580 ลงวันที่ 18 มีนาคม 2569",
      "statusGroup": "approved",
      "statusLabel": "ได้รับอนุญาตแล้ว"
    },
    {
      "no": 3,
      "workType": "สถานีไฟฟ้า",
      "projectName": "งานก่อสร้างสถานีไฟฟ้าสมุทรสาคร 13",
      "permitDetail": "แจ้งถมดิน",
      "authority": "เทศบาลเมืองพันท้ายนรสิงห์",
      "statusText": "ได้รับอนุญาตแล้ว \nแบบขถด.2 เลขที่ 10/2569 ลงวันที่27 กรกฎาคม 2569",
      "statusGroup": "approved",
      "statusLabel": "ได้รับอนุญาตแล้ว"
    },
    {
      "no": 4,
      "workType": "สถานีไฟฟ้า",
      "projectName": "งานก่อสร้างสถานีไฟฟ้าสมุทรสาคร 13",
      "permitDetail": "ขอทางเชื่อม",
      "authority": "แขวงทางหลวงชนบทสมุทรสาคร",
      "statusText": "ได้รับอนุญาตแล้ว \nตามหนังสือที่ คค 0703.61/714 ลงวันที่ 6 มีนาคม 2569",
      "statusGroup": "approved",
      "statusLabel": "ได้รับอนุญาตแล้ว"
    },
    {
      "no": 5,
      "workType": "สถานีไฟฟ้า",
      "projectName": "งานก่อสร้างสถานีไฟฟ้าสมุทรสาคร 13",
      "permitDetail": "ขอดันท่อลอด",
      "authority": "แขวงทางหลวงชนบทสมุทรสาคร",
      "statusText": "ได้รับอนุญาตแล้ว ตามหนังสือที่ คค 0703.61/905 ลงวันที่ 30 มีนาคม 2569",
      "statusGroup": "approved",
      "statusLabel": "ได้รับอนุญาตแล้ว"
    },
    {
      "no": 6,
      "workType": "สถานีไฟฟ้า",
      "projectName": "งานก่อสร้างปรับปรุงสถานีไฟฟ้าอ้อมน้อย 1",
      "permitDetail": "แจ้งก่อสร้างสถานี",
      "authority": "เทศบาลนครอ้อมน้อย",
      "statusText": "อยู่ระหว่างเทศบาลนครอ้อมน้อย พิจารณา\nเทศบาลนครอ้อมน้อยนัดดูพื้นที่เรียบร้อยแล้ว",
      "statusGroup": "pending",
      "statusLabel": "อยู่ระหว่างพิจารณา"
    },
    {
      "no": 7,
      "workType": "สถานีไฟฟ้า",
      "projectName": "งานก่อสร้างปรับปรุงสถานีไฟฟ้าอ้อมน้อย 1",
      "permitDetail": "แจ้งถมดิน",
      "authority": "เทศบาลนครอ้อมน้อย",
      "statusText": "อยู่ระหว่างเทศบาลนครอ้อมน้อย พิจารณา\nเทศบาลนครอ้อมน้อยนัดดูพื้นที่เรียบร้อยแล้ว",
      "statusGroup": "pending",
      "statusLabel": "อยู่ระหว่างพิจารณา"
    },
    {
      "no": 8,
      "workType": "สถานีไฟฟ้า",
      "projectName": "งานก่อสร้างปรับปรุงสถานีไฟฟ้าอ้อมน้อย 1",
      "permitDetail": "ขอดันท่อลอด",
      "authority": "เทศบาลนครอ้อมน้อย",
      "statusText": "อยู่ระหว่าง กวว.(ก3) ประสานส่วนเกี่ยวข้องพิจารณาตำแหน่งต้น Riser Pole",
      "statusGroup": "pending",
      "statusLabel": "อยู่ระหว่างพิจารณา"
    },
    {
      "no": 9,
      "workType": "สายส่ง 115 kV",
      "projectName": "งานก่อสร้างสายส่ง 115 เควี เพิ่มจุดจ่ายไฟที่ 2 สถานีไฟฟ้าแรงสูงกำแพงแสน (กฟผ.) ถึงสามแยกตลาดกำแพงแสน",
      "permitDetail": "ขอปักเสาในพื้นที่แขวงทางหลวง",
      "authority": "แขวงทางหลวงนครปฐม",
      "statusText": "ได้รับอนุญาตแล้ว ตามหนังสือที่ คค 06089/ส.2(22-69)/1037 ลงวันที่ 22 เมษายน 2569",
      "statusGroup": "approved",
      "statusLabel": "ได้รับอนุญาตแล้ว"
    },
    {
      "no": 10,
      "workType": "สายส่ง 115 kV",
      "projectName": "งานก่อสร้างสายส่ง รองรับสถานีไฟฟ้ากาญจนบุรี 5 (ชั่วคราว)",
      "permitDetail": "ขอปักเสาพาดสาย",
      "authority": "แขวงทางหลวงกาญจนบุรี",
      "statusText": "อยู่ระหว่างแขวงทางหลวงกาญจนบุรี พิจารณา",
      "statusGroup": "pending",
      "statusLabel": "อยู่ระหว่างพิจารณา"
    },
    {
      "no": 11,
      "workType": "สายส่ง 115 kV",
      "projectName": "งานก่อสร้างสายส่ง 115 เควี รองรับสถานีไฟฟ้าสมุทรสาคร 18 (ชั่วคราว)",
      "permitDetail": "ขอปักเสาพาดสาย",
      "authority": "พื้นที่เอกชน",
      "statusText": "ได้รับอนุญาตขยับแนวท่อระบายน้ำและประปา และอนุญาตให้ก่อสร้างสายส่งแล้ว",
      "statusGroup": "approved",
      "statusLabel": "ได้รับอนุญาตแล้ว"
    },
    {
      "no": 12,
      "workType": "สายส่ง 115 kV",
      "projectName": "งานเชื่อมโยงสายส่งระบบ 115 เควี สถานีไฟฟ้าบริษัท ลูมินัส เอ็นเนอร์ยี จำกัด (SPP)",
      "permitDetail": "ขอปักเสาพาดสาย",
      "authority": "แขวงทางหลวงสุพรรณบุรีที่ 1",
      "statusText": "ได้รับอนุญาตแล้ว \nตามหนังสือที่ คค 06143/59/2302 ลงวันที่ 19 มีนาคม 2569",
      "statusGroup": "approved",
      "statusLabel": "ได้รับอนุญาตแล้ว"
    },
    {
      "no": 13,
      "workType": "สายส่ง 115 kV",
      "projectName": "งานเชื่อมโยงสายส่งระบบ 115 เควี สถานีไฟฟ้าบริษัท สยาม ไชนนิ่ง เอ็นเนอร์ยี จำกัด (SPP)",
      "permitDetail": "ขอปักเสาพาดสาย",
      "authority": "แขวงทางหลวงสุพรรณบุรีที่ 1",
      "statusText": "ได้รับอนุญาตแล้ว \nตามหนังสือที่ คค 06143/61/2392 ลงวันที่ 23 มีนาคม 2569",
      "statusGroup": "approved",
      "statusLabel": "ได้รับอนุญาตแล้ว"
    },
    {
      "no": 14,
      "workType": "สายส่ง 115 kV",
      "projectName": "งานเชื่อมโยงสายส่งระบบ 115 เควี สถานีไฟฟ้าบริษัท สยาม ไชนนิ่ง เอ็นเนอร์ยี จำกัด (SPP)",
      "permitDetail": "ขอดันท่อลอด",
      "authority": "แขวงทางหลวงสุพรรณบุรีที่ 1",
      "statusText": "ได้รับอนุญาตแล้ว \nตามหนังสือที่ คค 06143/60/2579 ลงวันที่ 30 มีนาคม 2569",
      "statusGroup": "approved",
      "statusLabel": "ได้รับอนุญาตแล้ว"
    }
  ],
  "disbursements": [
    {
      "sheetName": "สาคร14",
      "projectName": "สถานีไฟฟ้าสมุทรสาคร 14 (ชั่วคราว)",
      "summary": {
        "wbs": "I-68-I-KKHXX.IS.1000",
        "desc": "งานก่อสร้างสถานีไฟฟ้าสมุทรสาคร 14 (ชั่วค",
        "status": "CRTD AVAC PREL BUDG  // Z0",
        "level": 4,
        "origBudget": 28208212.72,
        "currBudget": 29358372.72,
        "allocated": 29093136.18,
        "distributable": 265236.54,
        "prPo": 0.0,
        "actMaterial": 0.0,
        "actContracting": 0.0,
        "actCoordination": 0.0,
        "actSiteOther": 0.0,
        "actTotal": 0.0,
        "remBudget": 265236.54
      },
      "wbsItems": [
        {
          "wbs": "I-68-I-KKHXX.IS.1001",
          "desc": "งานปรับปรุงที่ดิน",
          "status": "REL AVAC SETC BUDG ISBD NTUP  // D1",
          "level": 5,
          "origBudget": 515100.0,
          "currBudget": 514300.0,
          "allocated": 0.0,
          "distributable": 514300.0,
          "prPo": 0.0,
          "actMaterial": 0.0,
          "actContracting": 55140.19,
          "actCoordination": 0.0,
          "actSiteOther": 0.0,
          "actTotal": 55140.19,
          "remBudget": 459159.81
        },
        {
          "wbs": "I-68-I-KKHXX.IS.1002",
          "desc": "งานก่อสร้างถนนลูกรังและหินคลุกบดอัดแน่น",
          "status": "REL AVAC SETC BUDG ISBD NTUP  // D1",
          "level": 5,
          "origBudget": 163000.0,
          "currBudget": 156700.0,
          "allocated": 0.0,
          "distributable": 156700.0,
          "prPo": 0.0,
          "actMaterial": 0.0,
          "actContracting": 43925.23,
          "actCoordination": 0.0,
          "actSiteOther": 0.0,
          "actTotal": 43925.23,
          "remBudget": 112774.77
        },
        {
          "wbs": "I-68-I-KKHXX.IS.1003",
          "desc": "งานโยธา",
          "status": "REL AVAC SETC BUDG ISBD NTUP  // C1",
          "level": 5,
          "origBudget": 978800.0,
          "currBudget": 951600.0,
          "allocated": 0.0,
          "distributable": 951600.0,
          "prPo": 0.0,
          "actMaterial": 0.0,
          "actContracting": 874100.0,
          "actCoordination": 0.0,
          "actSiteOther": 0.0,
          "actTotal": 874100.0,
          "remBudget": 77500.0
        },
        {
          "wbs": "I-68-I-KKHXX.IS.1004",
          "desc": "งานลงหินเบอร์ 2",
          "status": "TECO  AVAC SETC BUDG ISBD NTUP  // D2",
          "level": 5,
          "origBudget": 153600.0,
          "currBudget": 153000.0,
          "allocated": 0.0,
          "distributable": 153000.0,
          "prPo": 0.0,
          "actMaterial": 0.0,
          "actContracting": 153000.0,
          "actCoordination": 0.0,
          "actSiteOther": 0.0,
          "actTotal": 153000.0,
          "remBudget": 0.0
        },
        {
          "wbs": "I-68-I-KKHXX.IS.1005",
          "desc": "ระบบ CSCS",
          "status": "TECO  AVAC SETC BUDG ISBD NTUP  // D2",
          "level": 5,
          "origBudget": 200000.0,
          "currBudget": 200000.0,
          "allocated": 0.0,
          "distributable": 200000.0,
          "prPo": 0.0,
          "actMaterial": 0.0,
          "actContracting": 180000.0,
          "actCoordination": 0.0,
          "actSiteOther": 0.0,
          "actTotal": 180000.0,
          "remBudget": 20000.0
        },
        {
          "wbs": "I-68-I-KKHXX.IS.1007",
          "desc": "งานก่อสร้าง สฟฟ.สค.14(ชค)",
          "status": "REL AVAC SETC BUDG ISBD NTUP NSCH  // C1",
          "level": 5,
          "origBudget": 6080709.72,
          "currBudget": 6080709.72,
          "allocated": 0.0,
          "distributable": 6080709.72,
          "prPo": 0.0,
          "actMaterial": 0.0,
          "actContracting": 0.0,
          "actCoordination": 0.0,
          "actSiteOther": 2607880.68,
          "actTotal": 2640380.68,
          "remBudget": 3440329.04
        },
        {
          "wbs": "I-68-I-KKHXX.IS.1009",
          "desc": "งานติดตั้งระบบ Fire Alarm",
          "status": "REL AVAC SETC BUDG ISBD NTUP  // C2",
          "level": 5,
          "origBudget": 19000.0,
          "currBudget": 19000.0,
          "allocated": 0.0,
          "distributable": 19000.0,
          "prPo": 0.0,
          "actMaterial": 0.0,
          "actContracting": 19000.0,
          "actCoordination": 0.0,
          "actSiteOther": 0.0,
          "actTotal": 19000.0,
          "remBudget": 0.0
        },
        {
          "wbs": "I-68-I-KKHXX.IS.1010",
          "desc": "งานก่อสร้างเสาเหล็ก Monopole",
          "status": "REL AVAC SETC BUDG ISBD NTUP  // C1",
          "level": 5,
          "origBudget": 3248200.0,
          "currBudget": 3248200.0,
          "allocated": 0.0,
          "distributable": 3248200.0,
          "prPo": 61080.0,
          "actMaterial": 0.0,
          "actContracting": 3187120.0,
          "actCoordination": 0.0,
          "actSiteOther": 0.0,
          "actTotal": 3187120.0,
          "remBudget": 61080.0
        },
        {
          "wbs": "I-68-I-KKHXX.IS.1011",
          "desc": "ก่อสร้างสายส่ง 115kV",
          "status": "REL AVAC SETC BUDG NTUP  // C1",
          "level": 5,
          "origBudget": 17104586.85,
          "currBudget": 17104586.85,
          "allocated": 0.0,
          "distributable": 17104586.85,
          "prPo": 0.0,
          "actMaterial": 0.0,
          "actContracting": 0.0,
          "actCoordination": 0.0,
          "actSiteOther": 5558741.61,
          "actTotal": 5944216.61,
          "remBudget": 11160370.24
        },
        {
          "wbs": "I-68-I-KKHXX.IS.1012",
          "desc": "งานติดตั้ง SF6 (XMU03S-02) TIELINE",
          "status": "CLSD  AVAC SETC BUDG ISBD NTUP  // F4",
          "level": 5,
          "origBudget": 43363.28,
          "currBudget": 24718.71,
          "allocated": 0.0,
          "distributable": 24718.71,
          "prPo": 0.0,
          "actMaterial": 0.0,
          "actContracting": 0.0,
          "actCoordination": 0.0,
          "actSiteOther": 24456.13,
          "actTotal": 24456.13,
          "remBudget": 262.58
        },
        {
          "wbs": "I-68-I-KKHXX.IS.1013",
          "desc": "งานติดตั้ง SF6 (XMU01S-02) TIELINE",
          "status": "CLSD  AVAC SETC BUDG ISBD NTUP  // F4",
          "level": 5,
          "origBudget": 43363.28,
          "currBudget": 24836.23,
          "allocated": 0.0,
          "distributable": 24836.23,
          "prPo": 0.0,
          "actMaterial": 0.0,
          "actContracting": 0.0,
          "actCoordination": 0.0,
          "actSiteOther": 24573.65,
          "actTotal": 24573.65,
          "remBudget": 262.58
        },
        {
          "wbs": "I-68-I-KKHXX.IS.1014",
          "desc": "งานติดตั้ง SF6 (XMU10S-08) TIELINE",
          "status": "CLSD  AVAC SETC BUDG ISBD NTUP  // F4",
          "level": 5,
          "origBudget": 43363.28,
          "currBudget": 25051.3,
          "allocated": 0.0,
          "distributable": 25051.3,
          "prPo": 0.0,
          "actMaterial": 0.0,
          "actContracting": 0.0,
          "actCoordination": 0.0,
          "actSiteOther": 24788.72,
          "actTotal": 24788.72,
          "remBudget": 262.58
        },
        {
          "wbs": "I-68-I-KKHXX.IS.1015",
          "desc": "งานติดตั้ง SF6 เเทน DIS หน้าวัดโกรกกราก",
          "status": "CLSD  AVAC SETC BUDG ISBD NTUP  // F4",
          "level": 5,
          "origBudget": 44443.48,
          "currBudget": 13195.11,
          "allocated": 0.0,
          "distributable": 13195.11,
          "prPo": 0.0,
          "actMaterial": 0.0,
          "actContracting": 0.0,
          "actCoordination": 0.0,
          "actSiteOther": 0.0,
          "actTotal": 0.0,
          "remBudget": 13195.11
        },
        {
          "wbs": "I-68-I-KKHXX.IS.1016",
          "desc": "งานติดตั้ง SF6 เเทน DIS คลองกระโจน",
          "status": "CLSD  AVAC SETC BUDG ISBD NTUP  // F4",
          "level": 5,
          "origBudget": 44443.48,
          "currBudget": 25065.94,
          "allocated": 0.0,
          "distributable": 25065.94,
          "prPo": 0.0,
          "actMaterial": 0.0,
          "actContracting": 0.0,
          "actCoordination": 0.0,
          "actSiteOther": 0.0,
          "actTotal": 0.0,
          "remBudget": 25065.94
        },
        {
          "wbs": "I-68-I-KKHXX.IS.1017",
          "desc": "งานติดตั้ง SF6 (SMF03S-14) TIELINE",
          "status": "CLSD  AVAC SETC BUDG ISBD NTUP  // F4",
          "level": 5,
          "origBudget": 43363.28,
          "currBudget": 25263.39,
          "allocated": 0.0,
          "distributable": 25263.39,
          "prPo": 0.0,
          "actMaterial": 0.0,
          "actContracting": 0.0,
          "actCoordination": 0.0,
          "actSiteOther": 0.0,
          "actTotal": 0.0,
          "remBudget": 25263.39
        },
        {
          "wbs": "I-68-I-KKHXX.IS.1018",
          "desc": "งานติดตั้ง SF6 เเทน DIS ซอยคลองหลวง",
          "status": "CLSD  AVAC SETC BUDG ISBD NTUP  // F4",
          "level": 5,
          "origBudget": 47357.6,
          "currBudget": 26518.66,
          "allocated": 0.0,
          "distributable": 26518.66,
          "prPo": 0.0,
          "actMaterial": 0.0,
          "actContracting": 0.0,
          "actCoordination": 0.0,
          "actSiteOther": 0.0,
          "actTotal": 0.0,
          "remBudget": 26518.66
        },
        {
          "wbs": "I-68-I-KKHXX.IS.1019",
          "desc": "งานปรับปรุงเคเบิลใยเเก้วนำเเสงเข้า สค.14",
          "status": "CLSD  AVAC SETC BUDG ISBD NTUP  // F4",
          "level": 5,
          "origBudget": 516804.47,
          "currBudget": 461549.0,
          "allocated": 0.0,
          "distributable": 461549.0,
          "prPo": 0.0,
          "actMaterial": 0.0,
          "actContracting": 461549.0,
          "actCoordination": 0.0,
          "actSiteOther": 0.0,
          "actTotal": 461549.0,
          "remBudget": 0.0
        },
        {
          "wbs": "I-68-I-TARXX.IS.1001",
          "desc": "ปป.22kV หน้า สฟฟ.ท่ามะกา 2(ชค)",
          "status": "CLSD  AVAC SETC BUDG ISBD NTUP  // F4",
          "level": 5,
          "origBudget": 68874.0,
          "currBudget": 38841.27,
          "allocated": 0.0,
          "distributable": 38841.27,
          "prPo": 0.0,
          "actMaterial": 0.0,
          "actContracting": 0.0,
          "actCoordination": 0.0,
          "actSiteOther": 38839.44,
          "actTotal": 38839.44,
          "remBudget": 1.83
        }
      ],
      "totalBudget": 29358372.72,
      "totalActual": 13671089.65,
      "totalPrPo": 61080.0,
      "totalRemaining": 15626203.069999998,
      "percentDisbursed": 46.57,
      "percentCommitted": 46.77
    },
    {
      "sheetName": "สาคร18",
      "projectName": "สถานีไฟฟ้าสมุทรสาคร 18 (ชั่วคราว)",
      "summary": {
        "wbs": "I-69-I-BNCXX.19.3904",
        "desc": "งานก่อสร้างสถานีไฟฟ้าสมุทรสาคร 18 (ชั่วค",
        "status": "CRTD AVAC PREL BUDG  // Z0",
        "level": 4,
        "origBudget": 10008111.96,
        "currBudget": 10008111.96,
        "allocated": 10008111.96,
        "distributable": 0.0,
        "prPo": 0.0,
        "actMaterial": 0.0,
        "actContracting": 0.0,
        "actCoordination": 0.0,
        "actSiteOther": 0.0,
        "actTotal": 0.0,
        "remBudget": 0.0
      },
      "wbsItems": [
        {
          "wbs": "I-69-I-BNCXX.19.3904.A",
          "desc": "ก่อสร้างสถานีไฟฟ้าสมุทรสาคร 18 (ช)",
          "status": "REL AVAC SETC BUDG NTUP  // C1",
          "level": 5,
          "origBudget": 7131005.88,
          "currBudget": 7131005.88,
          "allocated": 0.0,
          "distributable": 7131005.88,
          "prPo": 128400.0,
          "actMaterial": 0.0,
          "actContracting": 0.0,
          "actCoordination": 0.0,
          "actSiteOther": 131733.99,
          "actTotal": 455133.99,
          "remBudget": 6675871.89
        },
        {
          "wbs": "I-69-I-BNCXX.19.3904.B",
          "desc": "กส.สายส่ง 115kV รองรับ สฟฟ.สค.18(ช)",
          "status": "CRTD AVAC SETC BUDG NTUP  // B2",
          "level": 5,
          "origBudget": 1277889.2,
          "currBudget": 1277889.2,
          "allocated": 0.0,
          "distributable": 1277889.2,
          "prPo": 0.0,
          "actMaterial": 0.0,
          "actContracting": 0.0,
          "actCoordination": 0.0,
          "actSiteOther": 0.0,
          "actTotal": 0.0,
          "remBudget": 1277889.2
        },
        {
          "wbs": "I-69-I-BNCXX.19.3904.C",
          "desc": "กส.ระบบจำหน่าย 22kV รองรับ สฟฟ.สค.18(ช)",
          "status": "CRTD AVAC SETC BUDG NTUP  // B2",
          "level": 5,
          "origBudget": 1196310.2,
          "currBudget": 1196310.2,
          "allocated": 0.0,
          "distributable": 1196310.2,
          "prPo": 0.0,
          "actMaterial": 0.0,
          "actContracting": 0.0,
          "actCoordination": 0.0,
          "actSiteOther": 0.0,
          "actTotal": 0.0,
          "remBudget": 1196310.2
        },
        {
          "wbs": "I-69-I-BNCXX.19.3904.D",
          "desc": "กส.ระบบสื่อสาร รองรับ สฟฟ.สค.18(ช)",
          "status": "CRTD AVAC SETC BUDG  // B2",
          "level": 5,
          "origBudget": 103286.04,
          "currBudget": 103286.04,
          "allocated": 0.0,
          "distributable": 103286.04,
          "prPo": 0.0,
          "actMaterial": 0.0,
          "actContracting": 0.0,
          "actCoordination": 0.0,
          "actSiteOther": 0.0,
          "actTotal": 0.0,
          "remBudget": 103286.04
        },
        {
          "wbs": "I-69-I-BNCXX.19.3904.E",
          "desc": "จุด A ติดตั้ง DIS Tie Line บริเวณ ปากซอย",
          "status": "REL AVAC SETC BUDG NTUP  // C1",
          "level": 5,
          "origBudget": 27135.0,
          "currBudget": 27135.0,
          "allocated": 0.0,
          "distributable": 27135.0,
          "prPo": 0.0,
          "actMaterial": 0.0,
          "actContracting": 0.0,
          "actCoordination": 0.0,
          "actSiteOther": 4.85,
          "actTotal": 4.85,
          "remBudget": 27130.15
        },
        {
          "wbs": "I-69-I-BNCXX.19.3904.F",
          "desc": "จุด B ติดตั้ง DIS Tie Line บริเวณ ปากซอย",
          "status": "REL AVAC SETC BUDG NTUP  // C1",
          "level": 5,
          "origBudget": 10691.12,
          "currBudget": 10691.12,
          "allocated": 0.0,
          "distributable": 10691.12,
          "prPo": 0.0,
          "actMaterial": 0.0,
          "actContracting": 0.0,
          "actCoordination": 0.0,
          "actSiteOther": 2.7,
          "actTotal": 2.7,
          "remBudget": 10688.42
        },
        {
          "wbs": "I-69-I-BNCXX.19.3904.G",
          "desc": "จุด C ติดตั้ง SF6 แทน DIS (KTB08S-11) บร",
          "status": "REL AVAC SETC BUDG NTUP  // C1",
          "level": 5,
          "origBudget": 44684.48,
          "currBudget": 44684.48,
          "allocated": 0.0,
          "distributable": 44684.48,
          "prPo": 0.0,
          "actMaterial": 0.0,
          "actContracting": 0.0,
          "actCoordination": 0.0,
          "actSiteOther": 16.51,
          "actTotal": 16.51,
          "remBudget": 44667.97
        },
        {
          "wbs": "I-69-I-BNCXX.19.3904.H",
          "desc": "จุด D ติดตั้ง SF6 แทน DIS (KTB08S-07) บร",
          "status": "REL AVAC SETC BUDG NTUP  // C1",
          "level": 5,
          "origBudget": 44684.48,
          "currBudget": 44684.48,
          "allocated": 0.0,
          "distributable": 44684.48,
          "prPo": 0.0,
          "actMaterial": 0.0,
          "actContracting": 0.0,
          "actCoordination": 0.0,
          "actSiteOther": 4753.89,
          "actTotal": 4753.89,
          "remBudget": 39930.59
        },
        {
          "wbs": "I-69-I-BNCXX.19.3904.I",
          "desc": "จุด E ติดตั้ง DIS ตัดไลน์ วงจร KTB08 บริ",
          "status": "REL AVAC SETC BUDG NTUP  // C1",
          "level": 5,
          "origBudget": 9786.12,
          "currBudget": 9786.12,
          "allocated": 0.0,
          "distributable": 9786.12,
          "prPo": 0.0,
          "actMaterial": 0.0,
          "actContracting": 0.0,
          "actCoordination": 0.0,
          "actSiteOther": 2.58,
          "actTotal": 2.58,
          "remBudget": 9783.54
        },
        {
          "wbs": "I-69-I-BNCXX.19.3904.J",
          "desc": "จุด F ติดตั้ง SF6 แทน DIS (KTB04S-07) บร",
          "status": "REL AVAC SETC BUDG NTUP  // C1",
          "level": 5,
          "origBudget": 49945.48,
          "currBudget": 49945.48,
          "allocated": 0.0,
          "distributable": 49945.48,
          "prPo": 0.0,
          "actMaterial": 0.0,
          "actContracting": 0.0,
          "actCoordination": 0.0,
          "actSiteOther": 26165.47,
          "actTotal": 26165.47,
          "remBudget": 23780.01
        },
        {
          "wbs": "I-69-I-BNCXX.19.3904.K",
          "desc": "จุด G ติดตั้ง SF6 ตัดไลน์ วงจร SMI05 บริ",
          "status": "REL AVAC SETC BUDG NTUP  // C1",
          "level": 5,
          "origBudget": 59444.48,
          "currBudget": 59444.48,
          "allocated": 0.0,
          "distributable": 59444.48,
          "prPo": 0.0,
          "actMaterial": 0.0,
          "actContracting": 0.0,
          "actCoordination": 0.0,
          "actSiteOther": 16626.18,
          "actTotal": 16626.18,
          "remBudget": 42818.3
        },
        {
          "wbs": "I-69-I-BNCXX.19.3904.L",
          "desc": "จุด H ติดตั้ง SF6 ตัดไลน์ วงจร SMI05 บริ",
          "status": "REL AVAC SETC BUDG NTUP  // C1",
          "level": 5,
          "origBudget": 53249.48,
          "currBudget": 53249.48,
          "allocated": 0.0,
          "distributable": 53249.48,
          "prPo": 0.0,
          "actMaterial": 0.0,
          "actContracting": 0.0,
          "actCoordination": 0.0,
          "actSiteOther": 12998.26,
          "actTotal": 12998.26,
          "remBudget": 40251.22
        }
      ],
      "totalBudget": 10008111.96,
      "totalActual": 515704.43,
      "totalPrPo": 128400.0,
      "totalRemaining": 9364007.530000001,
      "percentDisbursed": 5.15,
      "percentCommitted": 6.44
    },
    {
      "sheetName": "กาญ5",
      "projectName": "สถานีไฟฟ้ากาญจนบุรี 5 (ชั่วคราว)",
      "summary": {
        "wbs": "I-69-I-KCI01.19.3907",
        "desc": "งานก่อสร้างสถานีไฟฟ้ากาญจนบุรี 5(ช)",
        "status": "REL AVAC SETC BUDG NTUP  // C1",
        "level": 4,
        "origBudget": 9894069.92,
        "currBudget": 9894069.92,
        "allocated": 0.0,
        "distributable": 9894069.92,
        "prPo": 422500.0,
        "actMaterial": 0.0,
        "actContracting": 439000.0,
        "actCoordination": 0.0,
        "actSiteOther": 861.33,
        "actTotal": 513261.33,
        "remBudget": 9380808.59
      },
      "wbsItems": [
        {
          "wbs": "I-69-I-SMN01.19.3907",
          "desc": "รื้อถอนสถานีไฟฟ้าสมุทรสาคร 10(คืนคลัง)",
          "status": "CRTD AVAC SETC BUDG NTUP  // C1",
          "level": 4,
          "origBudget": 0.0,
          "currBudget": 0.0,
          "allocated": 0.0,
          "distributable": 0.0,
          "prPo": 0.0,
          "actMaterial": 0.0,
          "actContracting": 0.0,
          "actCoordination": 0.0,
          "actSiteOther": 0.0,
          "actTotal": 0.0,
          "remBudget": 0.0
        },
        {
          "wbs": "I-69-I-SMN02.19.3907",
          "desc": "ปป. 22kV บริเวณหน้า สฟฟ.สมุทรสาคร 10(ชค)",
          "status": "REL AVAC SETC BUDG NTUP  // C1",
          "level": 4,
          "origBudget": 99202.0,
          "currBudget": 99202.0,
          "allocated": 0.0,
          "distributable": 99202.0,
          "prPo": 0.0,
          "actMaterial": 0.0,
          "actContracting": 0.0,
          "actCoordination": 0.0,
          "actSiteOther": 8.79,
          "actTotal": 8.79,
          "remBudget": 99193.21
        },
        {
          "wbs": "I-69-I-KCI02.19.3907",
          "desc": "งานก่อสร้างสายส่ง 115 kV (ภายนอก)",
          "status": "REL AVAC SETC BUDG NTUP  // C1",
          "level": 4,
          "origBudget": 7982957.37,
          "currBudget": 7982957.37,
          "allocated": 0.0,
          "distributable": 7982957.37,
          "prPo": 466627.59,
          "actMaterial": 0.0,
          "actContracting": 0.0,
          "actCoordination": 0.0,
          "actSiteOther": 154890.6,
          "actTotal": 154890.6,
          "remBudget": 7828066.77
        },
        {
          "wbs": "I-69-I-KCI03.19.3907",
          "desc": "งาน ปป. 22kV (ใต้ 115kV) ช่วง สฟฟ.กจ.5(ช",
          "status": "CRTD AVAC SETC BUDG NTUP  // B2",
          "level": 4,
          "origBudget": 2791950.44,
          "currBudget": 2791950.44,
          "allocated": 0.0,
          "distributable": 2791950.44,
          "prPo": 0.0,
          "actMaterial": 0.0,
          "actContracting": 0.0,
          "actCoordination": 0.0,
          "actSiteOther": 0.0,
          "actTotal": 0.0,
          "remBudget": 2791950.44
        },
        {
          "wbs": "I-69-I-KCI04.19.3907",
          "desc": "งาน ปป. 22kV ช่วง สฟฟ.กจ.5(ช) - ซอยทุ่งน",
          "status": "CRTD AVAC SETC BUDG NTUP  // B2",
          "level": 4,
          "origBudget": 1451420.12,
          "currBudget": 1451420.12,
          "allocated": 0.0,
          "distributable": 1451420.12,
          "prPo": 0.0,
          "actMaterial": 0.0,
          "actContracting": 0.0,
          "actCoordination": 0.0,
          "actSiteOther": 0.0,
          "actTotal": 0.0,
          "remBudget": 1451420.12
        },
        {
          "wbs": "I-69-I-KCI05.19.3907",
          "desc": "งาน ปป. 22kV ช่วง สฟฟ.กจ.5(ช) - ศูนย์สร้",
          "status": "CRTD AVAC SETC BUDG NTUP  // B2",
          "level": 4,
          "origBudget": 225852.72,
          "currBudget": 225852.72,
          "allocated": 0.0,
          "distributable": 225852.72,
          "prPo": 0.0,
          "actMaterial": 0.0,
          "actContracting": 0.0,
          "actCoordination": 0.0,
          "actSiteOther": 0.0,
          "actTotal": 0.0,
          "remBudget": 225852.72
        },
        {
          "wbs": "I-69-I-KCI06.19.3907",
          "desc": "งานก่อสร้างเคเบิลใยแก้วนำแสง",
          "status": "CRTD AVAC SETC BUDG  // B2",
          "level": 4,
          "origBudget": 302512.74,
          "currBudget": 302512.74,
          "allocated": 0.0,
          "distributable": 302512.74,
          "prPo": 0.0,
          "actMaterial": 0.0,
          "actContracting": 0.0,
          "actCoordination": 0.0,
          "actSiteOther": 0.0,
          "actTotal": 0.0,
          "remBudget": 302512.74
        },
        {
          "wbs": "I-69-I-KCIPC.19.3907.A",
          "desc": "ติดตั้ง DIS Tie Line วงจร KCU03-KCU05",
          "status": "CRTD AVAC SETC BUDG NTUP  // B2",
          "level": 5,
          "origBudget": 5226.12,
          "currBudget": 5226.12,
          "allocated": 0.0,
          "distributable": 5226.12,
          "prPo": 0.0,
          "actMaterial": 0.0,
          "actContracting": 0.0,
          "actCoordination": 0.0,
          "actSiteOther": 0.0,
          "actTotal": 0.0,
          "remBudget": 5226.12
        },
        {
          "wbs": "I-69-I-KCIPC.19.3907.B",
          "desc": "ติดตั้ง DIS Tie Line วงจร KCU01-KCU02",
          "status": "CRTD AVAC SETC BUDG NTUP  // B2",
          "level": 5,
          "origBudget": 5222.32,
          "currBudget": 5222.32,
          "allocated": 0.0,
          "distributable": 5222.32,
          "prPo": 0.0,
          "actMaterial": 0.0,
          "actContracting": 0.0,
          "actCoordination": 0.0,
          "actSiteOther": 0.0,
          "actTotal": 0.0,
          "remBudget": 5222.32
        },
        {
          "wbs": "I-69-I-KCIPC.19.3907.C",
          "desc": "เปลี่ยน DIS ตัดไลน์ เป็น Loop Line วงจร",
          "status": "CRTD AVAC SETC BUDG NTUP  // B2",
          "level": 5,
          "origBudget": 2794.44,
          "currBudget": 2794.44,
          "allocated": 0.0,
          "distributable": 2794.44,
          "prPo": 0.0,
          "actMaterial": 0.0,
          "actContracting": 0.0,
          "actCoordination": 0.0,
          "actSiteOther": 0.0,
          "actTotal": 0.0,
          "remBudget": 2794.44
        },
        {
          "wbs": "I-69-I-KCIPC.19.3907.D",
          "desc": "ติดตั้ง DIS Loop Line วงจร KCU05-KCU06",
          "status": "CRTD AVAC SETC BUDG NTUP  // B2",
          "level": 5,
          "origBudget": 5226.12,
          "currBudget": 5226.12,
          "allocated": 0.0,
          "distributable": 5226.12,
          "prPo": 0.0,
          "actMaterial": 0.0,
          "actContracting": 0.0,
          "actCoordination": 0.0,
          "actSiteOther": 0.0,
          "actTotal": 0.0,
          "remBudget": 5226.12
        },
        {
          "wbs": "I-69-I-KCIPC.19.3907.E",
          "desc": "ติดตั้ง SF6 ตัดไลน์ วงจร KCU05",
          "status": "CRTD AVAC SETC BUDG NTUP  // B2",
          "level": 5,
          "origBudget": 47791.28,
          "currBudget": 47791.28,
          "allocated": 0.0,
          "distributable": 47791.28,
          "prPo": 0.0,
          "actMaterial": 0.0,
          "actContracting": 0.0,
          "actCoordination": 0.0,
          "actSiteOther": 0.0,
          "actTotal": 0.0,
          "remBudget": 47791.28
        },
        {
          "wbs": "I-69-I-KCIPC.19.3907.F",
          "desc": "ติดตั้ง SF6 แทน DIS (KCA09S-03) บริเวณ",
          "status": "CRTD AVAC SETC BUDG NTUP  // B2",
          "level": 5,
          "origBudget": 47997.2,
          "currBudget": 47997.2,
          "allocated": 0.0,
          "distributable": 47997.2,
          "prPo": 0.0,
          "actMaterial": 0.0,
          "actContracting": 0.0,
          "actCoordination": 0.0,
          "actSiteOther": 0.0,
          "actTotal": 0.0,
          "remBudget": 47997.2
        },
        {
          "wbs": "I-69-I-KCIPC.19.3907.G",
          "desc": "ติดตั้ง SF6 Tie Line วงจร KCA04-KCU06",
          "status": "CRTD AVAC SETC BUDG NTUP  // B2",
          "level": 5,
          "origBudget": 48054.48,
          "currBudget": 48054.48,
          "allocated": 0.0,
          "distributable": 48054.48,
          "prPo": 0.0,
          "actMaterial": 0.0,
          "actContracting": 0.0,
          "actCoordination": 0.0,
          "actSiteOther": 0.0,
          "actTotal": 0.0,
          "remBudget": 48054.48
        },
        {
          "wbs": "I-69-I-KCIPC.19.3907.H",
          "desc": "ติดตั้ง SF6 ตัดไลน์ วงจร KCU01",
          "status": "CRTD AVAC SETC BUDG NTUP  // B2",
          "level": 5,
          "origBudget": 46900.48,
          "currBudget": 46900.48,
          "allocated": 0.0,
          "distributable": 46900.48,
          "prPo": 0.0,
          "actMaterial": 0.0,
          "actContracting": 0.0,
          "actCoordination": 0.0,
          "actSiteOther": 0.0,
          "actTotal": 0.0,
          "remBudget": 46900.48
        },
        {
          "wbs": "I-69-I-KCIPC.19.3907.I",
          "desc": "ติดตั้ง SF6 แทน DIS (TMA02S-06)",
          "status": "CRTD AVAC SETC BUDG NTUP  // B2",
          "level": 5,
          "origBudget": 47489.48,
          "currBudget": 47489.48,
          "allocated": 0.0,
          "distributable": 47489.48,
          "prPo": 0.0,
          "actMaterial": 0.0,
          "actContracting": 0.0,
          "actCoordination": 0.0,
          "actSiteOther": 0.0,
          "actTotal": 0.0,
          "remBudget": 47489.48
        },
        {
          "wbs": "I-69-I-KCIPC.19.3907.J",
          "desc": "ติดตั้ง DIS ตัดไลน์ วงจร KCU01",
          "status": "CRTD AVAC SETC BUDG NTUP  // B2",
          "level": 5,
          "origBudget": 46345.96,
          "currBudget": 46345.96,
          "allocated": 0.0,
          "distributable": 46345.96,
          "prPo": 0.0,
          "actMaterial": 0.0,
          "actContracting": 0.0,
          "actCoordination": 0.0,
          "actSiteOther": 0.0,
          "actTotal": 0.0,
          "remBudget": 46345.96
        },
        {
          "wbs": "I-69-I-KCIPC.19.3907.K",
          "desc": "ติดตั้ง DIS Tie Line วงจร KCU01-KCU03",
          "status": "CRTD AVAC SETC BUDG NTUP  // B2",
          "level": 5,
          "origBudget": 5430.92,
          "currBudget": 5430.92,
          "allocated": 0.0,
          "distributable": 5430.92,
          "prPo": 0.0,
          "actMaterial": 0.0,
          "actContracting": 0.0,
          "actCoordination": 0.0,
          "actSiteOther": 0.0,
          "actTotal": 0.0,
          "remBudget": 5430.92
        },
        {
          "wbs": "I-69-I-IMDXX.19.B907",
          "desc": "จัดซื้อพัสดุงานก่อสร้าง สฟฟ.กจ.5 (ชค)",
          "status": "REL AVAC BUDG  // B2",
          "level": 3,
          "origBudget": 16907216.21,
          "currBudget": 16515514.21,
          "allocated": 0.0,
          "distributable": 16515514.21,
          "prPo": 9031170.07,
          "actMaterial": 0.0,
          "actContracting": 0.0,
          "actCoordination": 0.0,
          "actSiteOther": 0.0,
          "actTotal": 0.0,
          "remBudget": 16515514.21
        },
        {
          "wbs": "I-69-I-SUBXX.19.B907",
          "desc": "จัดซื้ออุปกรณ์ป้องกัน สฟฟ.กจ.5 (ชค)",
          "status": "REL AVAC BUDG  // C1",
          "level": 3,
          "origBudget": 1259998.0,
          "currBudget": 603798.0,
          "allocated": 0.0,
          "distributable": 603798.0,
          "prPo": 0.0,
          "actMaterial": 0.0,
          "actContracting": 0.0,
          "actCoordination": 0.0,
          "actSiteOther": 0.0,
          "actTotal": 0.0,
          "remBudget": 603798.0
        },
        {
          "wbs": "I-69-I-PSCXX.19.B907",
          "desc": "จัดซื้อระบบกราวน์กริด สฟฟ.กจ.5 (ชค)",
          "status": "REL AVAC BUDG  // B2",
          "level": 3,
          "origBudget": 422130.0,
          "currBudget": 422130.0,
          "allocated": 0.0,
          "distributable": 422130.0,
          "prPo": 0.0,
          "actMaterial": 0.0,
          "actContracting": 0.0,
          "actCoordination": 0.0,
          "actSiteOther": 0.0,
          "actTotal": 0.0,
          "remBudget": 422130.0
        },
        {
          "wbs": "I-69-I-GMDXX.19.B907",
          "desc": "จัดซื้อ Termination Kit สฟฟ.กจ.5 (ชค)",
          "status": "REL AVAC BUDG  // B2",
          "level": 3,
          "origBudget": 172800.0,
          "currBudget": 172800.0,
          "allocated": 0.0,
          "distributable": 172800.0,
          "prPo": 0.0,
          "actMaterial": 0.0,
          "actContracting": 0.0,
          "actCoordination": 0.0,
          "actSiteOther": 0.0,
          "actTotal": 0.0,
          "remBudget": 172800.0
        }
      ],
      "totalBudget": 40462207.52,
      "totalActual": 668160.72,
      "totalPrPo": 9920297.66,
      "totalRemaining": 29873749.140000004,
      "percentDisbursed": 1.65,
      "percentCommitted": 26.17
    }
  ],
  "ganttPlans": {
    "สมุทรสาคร 18 (ช)": {
      "projectName": "สถานีไฟฟ้าสมุทรสาคร 18 (ชั่วคราว)",
      "tasks": [
        {
          "no": 1,
          "name": "รื้อถอนสถานีไฟฟ้าสมุทรสาคร 16 (ชั่วคราว)",
          "type": "แผนการดำเนินงาน",
          "perf": 80.0,
          "weight": 0.1,
          "calcPct": 8.0
        },
        {
          "no": 1,
          "name": "รื้อถอนสถานีไฟฟ้าสมุทรสาคร 16 (ชั่วคราว)",
          "type": "ผลการดำเนินงาน",
          "perf": 0,
          "weight": 0,
          "calcPct": 0
        },
        {
          "no": 2,
          "name": "ปรับปรุงที่ดิน",
          "type": "แผนการดำเนินงาน",
          "perf": 100.0,
          "weight": 0.05,
          "calcPct": 5.0
        },
        {
          "no": 2,
          "name": "ปรับปรุงที่ดิน",
          "type": "ผลการดำเนินงาน",
          "perf": 0,
          "weight": 0,
          "calcPct": 0
        },
        {
          "no": 3,
          "name": "ขนย้ายติดตั้งฐานราก",
          "type": "แผนการดำเนินงาน",
          "perf": 70.0,
          "weight": 0.05,
          "calcPct": 3.5
        },
        {
          "no": 3,
          "name": "ขนย้ายติดตั้งฐานราก",
          "type": "ผลการดำเนินงาน",
          "perf": 0,
          "weight": 0,
          "calcPct": 0
        },
        {
          "no": 4,
          "name": "ขนย้ายอุปกรณ์ป้องกัน 115 kV และหม้อแปลงไฟฟ้ากำลัง",
          "type": "แผนการดำเนินงาน",
          "perf": 0,
          "weight": 0.05,
          "calcPct": 0.0
        },
        {
          "no": 4,
          "name": "ขนย้ายอุปกรณ์ป้องกัน 115 kV และหม้อแปลงไฟฟ้ากำลัง",
          "type": "ผลการดำเนินงาน",
          "perf": 0,
          "weight": 0,
          "calcPct": 0
        },
        {
          "no": 5,
          "name": "ติดตั้งอุปกรณ์ป้องกัน 115 kV และหม้อแปลงไฟฟ้ากำลัง",
          "type": "แผนการดำเนินงาน",
          "perf": 0,
          "weight": 0.05,
          "calcPct": 0.0
        },
        {
          "no": 5,
          "name": "ติดตั้งอุปกรณ์ป้องกัน 115 kV และหม้อแปลงไฟฟ้ากำลัง",
          "type": "ผลการดำเนินงาน",
          "perf": 0,
          "weight": 0,
          "calcPct": 0
        },
        {
          "no": 6,
          "name": "ปักเสาภายในสถานีไฟฟ้า",
          "type": "แผนการดำเนินงาน",
          "perf": 0,
          "weight": 0.05,
          "calcPct": 0.0
        },
        {
          "no": 6,
          "name": "ปักเสาภายในสถานีไฟฟ้า",
          "type": "ผลการดำเนินงาน",
          "perf": 0,
          "weight": 0,
          "calcPct": 0
        },
        {
          "no": 7,
          "name": "ติดตั้งระบบกราวด์กริด",
          "type": "แผนการดำเนินงาน",
          "perf": 0,
          "weight": 0.05,
          "calcPct": 0.0
        },
        {
          "no": 7,
          "name": "ติดตั้งระบบกราวด์กริด",
          "type": "ผลการดำเนินงาน",
          "perf": 0,
          "weight": 0,
          "calcPct": 0
        },
        {
          "no": 8,
          "name": "ลงหินเบอร์ 2",
          "type": "แผนการดำเนินงาน",
          "perf": 0,
          "weight": 0.05,
          "calcPct": 0.0
        },
        {
          "no": 8,
          "name": "ลงหินเบอร์ 2",
          "type": "ผลการดำเนินงาน",
          "perf": 0,
          "weight": 0,
          "calcPct": 0
        },
        {
          "no": 9,
          "name": "ติดตั้ง Ladder",
          "type": "แผนการดำเนินงาน",
          "perf": 0,
          "weight": 0.05,
          "calcPct": 0.0
        },
        {
          "no": 9,
          "name": "ติดตั้ง Ladder",
          "type": "ผลการดำเนินงาน",
          "perf": 0,
          "weight": 0,
          "calcPct": 0
        },
        {
          "no": 10,
          "name": "ลากสายและติดตั้งสาย Control cable",
          "type": "แผนการดำเนินงาน",
          "perf": 0,
          "weight": 0.1,
          "calcPct": 0.0
        },
        {
          "no": 10,
          "name": "ลากสายและติดตั้งสาย Control cable",
          "type": "ผลการดำเนินงาน",
          "perf": 0,
          "weight": 0,
          "calcPct": 0
        },
        {
          "no": 11,
          "name": "ลากสายและติดตั้งสาย Power cable",
          "type": "แผนการดำเนินงาน",
          "perf": 0,
          "weight": 0.1,
          "calcPct": 0.0
        },
        {
          "no": 11,
          "name": "ลากสายและติดตั้งสาย Power cable",
          "type": "ผลการดำเนินงาน",
          "perf": 0,
          "weight": 0,
          "calcPct": 0
        },
        {
          "no": 12,
          "name": "CSCS",
          "type": "แผนการดำเนินงาน",
          "perf": 0,
          "weight": 0.1,
          "calcPct": 0.0
        },
        {
          "no": 12,
          "name": "CSCS",
          "type": "ผลการดำเนินงาน",
          "perf": 0,
          "weight": 0,
          "calcPct": 0
        },
        {
          "no": 13,
          "name": "Individual Test",
          "type": "แผนการดำเนินงาน",
          "perf": 0,
          "weight": 0.05,
          "calcPct": 0.0
        },
        {
          "no": 13,
          "name": "Individual Test",
          "type": "ผลการดำเนินงาน",
          "perf": 0,
          "weight": 0,
          "calcPct": 0
        },
        {
          "no": 14,
          "name": "Commisioning Test",
          "type": "แผนการดำเนินงาน",
          "perf": 0,
          "weight": 0.05,
          "calcPct": 0.0
        },
        {
          "no": 14,
          "name": "Commisioning Test",
          "type": "ผลการดำเนินงาน",
          "perf": 0,
          "weight": 0,
          "calcPct": 0
        },
        {
          "no": 15,
          "name": "Settind Relay / End to End Test",
          "type": "แผนการดำเนินงาน",
          "perf": 0,
          "weight": 0.05,
          "calcPct": 0.0
        },
        {
          "no": 15,
          "name": "Settind Relay / End to End Test",
          "type": "ผลการดำเนินงาน",
          "perf": 0,
          "weight": 0,
          "calcPct": 0
        },
        {
          "no": 16,
          "name": "AC Withstand Test",
          "type": "แผนการดำเนินงาน",
          "perf": 0,
          "weight": 0.05,
          "calcPct": 0.0
        },
        {
          "no": 16,
          "name": "AC Withstand Test",
          "type": "ผลการดำเนินงาน",
          "perf": 0,
          "weight": 0,
          "calcPct": 0
        }
      ]
    },
    "กาญจนบุรี 5 (ช)": {
      "projectName": "สถานีไฟฟ้ากาญจนบุรี 5 (ชั่วคราว)",
      "tasks": [
        {
          "no": 1,
          "name": "รื้อถอนสถานีไฟฟ้าสมุทรสาคร 10 (ชั่วคราว)",
          "type": "แผนการดำเนินงาน",
          "perf": 80.0,
          "weight": 0.1,
          "calcPct": 8.0
        },
        {
          "no": 1,
          "name": "รื้อถอนสถานีไฟฟ้าสมุทรสาคร 10 (ชั่วคราว)",
          "type": "ผลการดำเนินงาน",
          "perf": 0,
          "weight": 0,
          "calcPct": 0
        },
        {
          "no": 2,
          "name": "ปรับปรุงที่ดิน",
          "type": "แผนการดำเนินงาน",
          "perf": 10.0,
          "weight": 0.05,
          "calcPct": 0.5
        },
        {
          "no": 2,
          "name": "ปรับปรุงที่ดิน",
          "type": "ผลการดำเนินงาน",
          "perf": 0,
          "weight": 0,
          "calcPct": 0
        },
        {
          "no": 3,
          "name": "ขนย้ายติดตั้งฐานราก",
          "type": "แผนการดำเนินงาน",
          "perf": 0,
          "weight": 0.05,
          "calcPct": 0.0
        },
        {
          "no": 3,
          "name": "ขนย้ายติดตั้งฐานราก",
          "type": "ผลการดำเนินงาน",
          "perf": 0,
          "weight": 0,
          "calcPct": 0
        },
        {
          "no": 4,
          "name": "ขนย้ายอุปกรณ์ป้องกัน 115 kV และหม้อแปลงไฟฟ้ากำลัง",
          "type": "แผนการดำเนินงาน",
          "perf": 0,
          "weight": 0.05,
          "calcPct": 0.0
        },
        {
          "no": 4,
          "name": "ขนย้ายอุปกรณ์ป้องกัน 115 kV และหม้อแปลงไฟฟ้ากำลัง",
          "type": "ผลการดำเนินงาน",
          "perf": 0,
          "weight": 0,
          "calcPct": 0
        },
        {
          "no": 5,
          "name": "ติดตั้งอุปกรณ์ป้องกัน 115 kV และหม้อแปลงไฟฟ้ากำลัง",
          "type": "แผนการดำเนินงาน",
          "perf": 0,
          "weight": 0.05,
          "calcPct": 0.0
        },
        {
          "no": 5,
          "name": "ติดตั้งอุปกรณ์ป้องกัน 115 kV และหม้อแปลงไฟฟ้ากำลัง",
          "type": "ผลการดำเนินงาน",
          "perf": 0,
          "weight": 0,
          "calcPct": 0
        },
        {
          "no": 6,
          "name": "ปักเสาภายในสถานีไฟฟ้า",
          "type": "แผนการดำเนินงาน",
          "perf": 0,
          "weight": 0.05,
          "calcPct": 0.0
        },
        {
          "no": 6,
          "name": "ปักเสาภายในสถานีไฟฟ้า",
          "type": "ผลการดำเนินงาน",
          "perf": 0,
          "weight": 0,
          "calcPct": 0
        },
        {
          "no": 7,
          "name": "ติดตั้งระบบกราวด์กริด",
          "type": "แผนการดำเนินงาน",
          "perf": 0,
          "weight": 0.05,
          "calcPct": 0.0
        },
        {
          "no": 7,
          "name": "ติดตั้งระบบกราวด์กริด",
          "type": "ผลการดำเนินงาน",
          "perf": 0,
          "weight": 0,
          "calcPct": 0
        },
        {
          "no": 8,
          "name": "ลงหินเบอร์ 2",
          "type": "แผนการดำเนินงาน",
          "perf": 0,
          "weight": 0.05,
          "calcPct": 0.0
        },
        {
          "no": 8,
          "name": "ลงหินเบอร์ 2",
          "type": "ผลการดำเนินงาน",
          "perf": 0,
          "weight": 0,
          "calcPct": 0
        },
        {
          "no": 9,
          "name": "ติดตั้ง Ladder",
          "type": "แผนการดำเนินงาน",
          "perf": 0,
          "weight": 0.05,
          "calcPct": 0.0
        },
        {
          "no": 9,
          "name": "ติดตั้ง Ladder",
          "type": "ผลการดำเนินงาน",
          "perf": 0,
          "weight": 0,
          "calcPct": 0
        },
        {
          "no": 10,
          "name": "ลากสายและติดตั้งสาย Control cable",
          "type": "แผนการดำเนินงาน",
          "perf": 0,
          "weight": 0.1,
          "calcPct": 0.0
        },
        {
          "no": 10,
          "name": "ลากสายและติดตั้งสาย Control cable",
          "type": "ผลการดำเนินงาน",
          "perf": 0,
          "weight": 0,
          "calcPct": 0
        },
        {
          "no": 11,
          "name": "ลากสายและติดตั้งสาย Power cable",
          "type": "แผนการดำเนินงาน",
          "perf": 0,
          "weight": 0.1,
          "calcPct": 0.0
        },
        {
          "no": 11,
          "name": "ลากสายและติดตั้งสาย Power cable",
          "type": "ผลการดำเนินงาน",
          "perf": 0,
          "weight": 0,
          "calcPct": 0
        },
        {
          "no": 12,
          "name": "CSCS",
          "type": "แผนการดำเนินงาน",
          "perf": 0,
          "weight": 0.1,
          "calcPct": 0.0
        },
        {
          "no": 12,
          "name": "CSCS",
          "type": "ผลการดำเนินงาน",
          "perf": 0,
          "weight": 0,
          "calcPct": 0
        },
        {
          "no": 13,
          "name": "Individual Test",
          "type": "แผนการดำเนินงาน",
          "perf": 0,
          "weight": 0.05,
          "calcPct": 0.0
        },
        {
          "no": 13,
          "name": "Individual Test",
          "type": "ผลการดำเนินงาน",
          "perf": 0,
          "weight": 0,
          "calcPct": 0
        },
        {
          "no": 14,
          "name": "Commisioning Test",
          "type": "แผนการดำเนินงาน",
          "perf": 0,
          "weight": 0.05,
          "calcPct": 0.0
        },
        {
          "no": 14,
          "name": "Commisioning Test",
          "type": "ผลการดำเนินงาน",
          "perf": 0,
          "weight": 0,
          "calcPct": 0
        },
        {
          "no": 15,
          "name": "Settind Relay / End to End Test",
          "type": "แผนการดำเนินงาน",
          "perf": 0,
          "weight": 0.05,
          "calcPct": 0.0
        },
        {
          "no": 15,
          "name": "Settind Relay / End to End Test",
          "type": "ผลการดำเนินงาน",
          "perf": 0,
          "weight": 0,
          "calcPct": 0
        },
        {
          "no": 16,
          "name": "AC Withstand Test",
          "type": "แผนการดำเนินงาน",
          "perf": 0,
          "weight": 0.05,
          "calcPct": 0.0
        },
        {
          "no": 16,
          "name": "AC Withstand Test",
          "type": "ผลการดำเนินงาน",
          "perf": 0,
          "weight": 0,
          "calcPct": 0
        }
      ]
    }
  }
};
